namespace Cruise.Model {
    public enum EEmployeeRole {
        CAPITAIN, MATE_1, MATE_2, MATE_3, STEERMAN, BOOTSMAN, COOK, WAITER, ENTERTAINMENT, SECURITY, ROOM_SERVICE, ELECTRICIAN, WOOD_WORK,
        CRAFTS_MAN, MACHINE_ENGINEER
    }
}